using './main.bicep'

param appName = 'gasblender'
param environment = 'prod'
param location = 'northeurope'
param resourceGroupName = 'rg-gasblender-prod'
param dnsSubscriptionId = '4f370769-6921-4fff-af30-d2ad027af683'
param dnsResourceGroupName = 'rg-dns-services-shared-001'
param customDomainHostname = 'divetools.redkic.co.uk'
param subDomainLabel = 'divetools'
